makerspacerp/base/urls.py
from makerspacerp.base.views import WerkstattUserListView, WerkstattUserDetailView, WerkstattUserCreateView, \
    WerkstattUserDeleteView, WerkstattUserUpdateView, TransactionCreateView, TransactionDetailView, TransactionListView, \
    TransactionDeleteView, TransactionUpdateView, ToolDetailView, ToolCreateView, ToolDeleteView, ToolListView, \
    ToolUpdateView, IntroductionListView, IntroductionCreateView, IntroductionDetailView, IntroductionDeleteView, \
    IntroductionUpdateView, IntroductionPDFView, IntroductionParticipationCreateView, \
    IntroductionParticipationDetailView, IntroductionParticipationDeleteView, TimeSlotUpdateView, TimeSlotListView, \
    TimeSlotDetailView, TimeSlotCreateView, TimeSlotDeleteView, ToggleCheckoutView, DashboardSettingsDetailView, \
    DashboardSettingsUpdateView, ConsumableListView, ConsumableCreateView, ConsumableDetailView, GlobalSearchResults, \
    UserListView, UserDetailView, UserUpdateView, UserCreateView, UserDeleteView

from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path('', RedirectView.as_view(url='werkstattusers/'), name='index'),
    path('login/', LoginView.as_view(template_name='owba_dashboard/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('search/', GlobalSearchResults.as_view(), name='global-search'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/create/', UserCreateView.as_view(), name='user-create'),
    path('user/delete/<int:pk>', UserDeleteView.as_view(), name='user-delete'),
    path('user/update/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('werkstattusers/', WerkstattUserListView.as_view(), name='werkstatt-user-list'),
    path('werkstattuser/<int:pk>/', WerkstattUserDetailView.as_view(), name='werkstatt-user-detail'),
    path('werkstattuser/new/', WerkstattUserCreateView.as_view(), name='werkstatt-user-create'),
    path('werkstattuser/update/<int:pk>/', WerkstattUserUpdateView.as_view(), name='werkstatt-user-update'),
    path('werkstattuser/delete/<int:pk>/', WerkstattUserDeleteView.as_view(), name='werkstatt-user-delete'),
    path('werkstattuser/<int:user_id>/toggle-checkin/', ToggleCheckoutView.as_view(), name='werkstatt-user-checkin'),
    path('transaction/new/', TransactionCreateView.as_view(), name='transaction-create'),
    path('transaction/<int:pk>/', TransactionDetailView.as_view(), name='transaction-detail'),
    path('transaction/update/<int:pk>/', TransactionUpdateView.as_view(), name='transaction-update'),
    path('transaction/delete/<int:pk>/', TransactionDeleteView.as_view(), name='transaction-delete'),
    path('transactions/', TransactionListView.as_view(), name='transaction-list'),
    path('tool/new/', ToolCreateView.as_view(), name='tool-create'),
    path('tool/delete/<int:pk>/', ToolDeleteView.as_view(), name='tool-delete'),
    path('tool/<int:pk>/', ToolDetailView.as_view(), name='tool-detail'),
    path('tool/update/<int:pk>/', ToolUpdateView.as_view(), name='tool-update'),
    path('tools/', ToolListView.as_view(), name='tool-list'),
    path('introductions/', IntroductionListView.as_view(), name='introduction-list'),
    path('introduction/new/', IntroductionCreateView.as_view(), name='introduction-create'),
    path('introduction/<int:pk>/', IntroductionDetailView.as_view(), name='introduction-detail'),
    path('introduction/delete/<int:pk>/', IntroductionDeleteView.as_view(), name='introduction-delete'),
    path('introduction/update/<int:pk>/', IntroductionUpdateView.as_view(), name='introduction-update'),
    path('introduction/<int:pk>/pdf', IntroductionPDFView.as_view(), name='introduction-pdf'),
    path('introduction-participation/create/', IntroductionParticipationCreateView.as_view(), name='introduction-participation-create'),
    path('introduction-participation/<int:pk>/', IntroductionParticipationDetailView.as_view(), name='introduction-participation-detail'),
    path('introduction-participation/<int:pk>/delete', IntroductionParticipationDeleteView.as_view(), name='introduction-participation-delete'),
    path('timeslots/', TimeSlotListView.as_view(), name='time-slot-list'),
    path('timeslot/<int:pk>/', TimeSlotDetailView.as_view(), name='time-slot-detail'),
    path('timeslot/new/', TimeSlotCreateView.as_view(), name='time-slot-create'),
    path('timeslot/update/<int:pk>/', TimeSlotUpdateView.as_view(), name='time-slot-update'),
    path('timeslot/delete/<int:pk>/', TimeSlotDeleteView.as_view(), name='time-slot-delete'),
    path('settings/', DashboardSettingsDetailView.as_view(), name='settings-detail'),
    path('settings/update/', DashboardSettingsUpdateView.as_view(), name='settings-update'),
    path('storage/', ConsumableListView.as_view(), name='storage-list'),
    path('consumable/create/', ConsumableCreateView.as_view(), name='consumable-create'),
    path('consumable/<int:pk>/', ConsumableDetailView.as_view(), name='consumable-detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

makerspacerp/base/models/account.py
from django.db import models

from makerspacerp.base.models import WerkstattUser


class Account(models.Model):
    user = models.OneToOneField(WerkstattUser, on_delete=models.CASCADE)
    balance = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    locked = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Konto'
        verbose_name_plural = 'Konten'

    def __str__(self):
        return "{}'s Konto".format(self.user)

    def change_balance(self, amount):
        self.balance = self.balance - amount
        self.save()

        return True

    def lock(self):
        self.locked = True
        self.save()

        return True

    def unlock(self):
        self.locked = False
        self.save()

        return True

makerspacerp/base/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(verbose_name='Name', max_length=280)

    class Meta:
        verbose_name = 'Kategorie'
        verbose_name_plural = 'Kategorien'

    def __str__(self):
        return self.name

makerspacerp/base/models/consumable.py
from django.db import models


class Consumable(models.Model):
    class Units(models.TextChoices):
        PIECES = 'pcs', 'Stück'
        METRE = 'm', 'm'
        CENTIMETRE = 'cm', 'cm'
        MILLIMETRE = 'mm', 'mm'
        SQUARE_METRE = 'm²', 'm²'
        CUBIC_METRE = 'm³', 'm³'
        GRAMM = 'g', 'g'
        KILOGRAMM = 'kg', 'kg'
    name_short = models.CharField(verbose_name='Kurzbeschreibung', max_length=280)
    name_exact = models.CharField(verbose_name='Exakte Bezeichnung', max_length=560)
    thumbnail = models.ImageField(verbose_name='Bild', upload_to='consumables', blank=True)
    unit = models.CharField(verbose_name='Einheit', max_length=280, choices=Units.choices, default=Units.PIECES)
    amount = models.DecimalField(verbose_name='Bestand', max_digits=6, decimal_places=2, default=0.00, editable=False)
    dimensions_x = models.DecimalField(verbose_name='Breite', max_digits=15, decimal_places=2, null=True, blank=True)
    dimensions_y = models.DecimalField(verbose_name='Höhe', max_digits=15, decimal_places=2, null=True, blank=True)
    categories = models.ManyToManyField('Category', verbose_name='Kategorien', blank=True)

    class Meta:
        verbose_name = 'Verbrauchsmaterial'
        verbose_name_plural = 'Verbrauchsmaterial'

    def __str__(self):
        return self.name_short

makerspacerp/base/models/consumption_refill.py
from django.db import models


class ConsumptionRefill(models.Model):
    class Types(models.TextChoices):
        CONSUMPTION = 'consumption', 'Verbrauch'
        REFILL = 'refill', 'Aufstockung'
    type = models.CharField(verbose_name='Art', max_length=280, choices=Types.choices)
    consumable = models.ForeignKey('Consumable', verbose_name='Verbrauchsmaterial', on_delete=models.CASCADE)
    user = models.ForeignKey('WerkstattUser', verbose_name='Nutzer:in', null=True, blank=True, on_delete=models.SET_NULL)
    amount = models.DecimalField(verbose_name='Menge', max_digits=12, decimal_places=2)

    def __str__(self):
        return "{}: {}".format(self.type, self.consumable)

makerspacerp/base/models/introduction_content.py
from django.db import models

from makerspacerp.base.models import Introduction


class IntroductionContent(models.Model):
    introduction = models.ForeignKey(Introduction, verbose_name='Einweisung', on_delete=models.CASCADE)
    order = models.IntegerField(verbose_name='Reihenfolge')
    text = models.TextField(verbose_name='Text')

    class Meta:
        verbose_name = 'Einweisungsinhalt'
        verbose_name_plural = 'Einweisungsinhalte'

makerspacerp/base/forms/time_slot.py
from django import forms
from makerspacerp.base.forms.widgets import SplitDateTimeWidget
from makerspacerp.base.models import TimeSlot


class TimeSlotForm(forms.ModelForm):
    begin_time = forms.SplitDateTimeField(label='Beginn', widget=SplitDateTimeWidget(date_attrs={'type': 'date',
                                                                                                 'class': 'mb-1'},
                                                                                     time_attrs={'type': 'time'}))
    end_time = forms.SplitDateTimeField(label='Ende', widget=SplitDateTimeWidget(date_attrs={'type': 'date',
                                                                                             'class': 'mb-1'},
                                        time_attrs={'type': 'time'}), required=False)

    class Meta:
        model = TimeSlot
        fields = '__all__'

makerspacerp/base/forms/widgets.py
from django.forms import SplitDateTimeWidget


class SplitDateTimeWidget(SplitDateTimeWidget):
    template_name = 'owba_dashboard/widgets/splitdatetime.html'

makerspacerp/base/views/consumable_create.py
from makerspacerp.base.views.generic import OWBACreateView
from makerspacerp.base.models import Consumable


class ConsumableCreateView(OWBACreateView):
    model = Consumable
    icon = 'box'
    breadcrumbs = {
        'Home': 'werkstatt-user-list',
        'Verbrauchsmaterial': 'storage-list',
        'Verbrauchsmaterial anlegen': 'consumable-create'
    }

makerspacerp/base/views/consumable_detail.py
from makerspacerp.base.views.generic import OWBADetailView
from makerspacerp.base.models import Consumable


class ConsumableDetailView(OWBADetailView):
    model = Consumable
    icon = 'box'
    breadcrumbs = {
        'Home': 'werkstatt-user-list',
        'Verbrauchsmaterial': 'storage-list'
    }

makerspacerp/base/views/consumable_list.py
from makerspacerp.base.views.generic import OWBAListView
from makerspacerp.base.models import Consumable


class ConsumableListView(OWBAListView):
    model = Consumable
    icon = 'box'
    breadcrumbs = {
        'Home': 'werkstatt-user-list',
        'Verbrauchsmaterial': 'storage-list'
    }
    views = {
        'create': 'consumable-create',
        'detail': 'consumable-detail'
    }
    tabular_list_columns = ['name_short', 'name_exact', 'amount', 'unit', 'categories']

makerspacerp/base/views/dashboard_settings_detail.py
from makerspacerp.base.views.generic import OWBADetailView
from makerspacerp.base.models import DashboardSettings


class DashboardSettingsDetailView(OWBADetailView):
    model = DashboardSettings
    template_name = 'owba_dashboard/settings_detail.html'
    icon = 'sliders-h'
    breadcrumbs = {
        'Home': 'werkstatt-user-list',
        'Einstellungen': 'settings-detail'
    }
    update_view = 'settings-update'
    fields = [{'name': 'workshop_basic_interval', 'format': '{} min'},
              {'name': 'workshop_basic_price', 'format': '{}€'},
              {'name': 'workshop_plus_interval', 'format': '{} min'},
              {'name': 'workshop_plus_price', 'format': '{}€'},
              {'name': 'machine_interval', 'format': '{} min'}, {'name': 'machine_price', 'format': '{}€'},
              'max_people', {'name': 'max_reservation_time', 'format': '{} min'}]

    def get_object(self, queryset=None):
        obj = DashboardSettings.load()
        return obj

makerspacerp/base/views/dashboard_settings_update.py
from django.urls import reverse_lazy
from makerspacerp.base.views.generic import OWBAUpdateView
from makerspacerp.base.models import DashboardSettings


class DashboardSettingsUpdateView(OWBAUpdateView):
    model = DashboardSettings
    icon = 'sliders-h'
    success_url = reverse_lazy('settings-detail')

    def get_object(self, queryset=None):
        obj = DashboardSettings.load()
        return obj

makerspacerp/base/views/global_search_results.py
from django.views.generic import TemplateView
from django.shortcuts import render
from makerspacerp.base.models import WerkstattUser, Tool, TimeSlot, Consumable
from django.db.models import Value as V
from django.db.models import Q
from django.db.models.functions import Concat


class GlobalSearchResults(TemplateView):
    template_name = 'owba_dashboard/global_search_results.html'

    def get_context_data(self, **kwargs):
        search_text = self.request.GET.get('query')
        search_models = [{'object': WerkstattUser,
                          'title': 'Werkstattnutzer:innen',
                          'icon': 'users',
                          'annotate': {'full_name': Concat('first_name', V(' '), 'last_name')},
                          'filter': Q(full_name__icontains=search_text) | Q(uuid=search_text),
                          'exclude': ['zip_code', 'id', 'missing_introductions', 'pk', 'first_name', 'last_name', 'street',
                                      'house_nr', 'city', 'introductions', 'checked_in'],
                          'views': {'detail': 'werkstatt-user-detail'},
                          'render_options':  {
                                'uuid': {
                                    'verbose_name': 'ID',
                                    'width': 2
                                },
                                'display_name': {
                                    'verbose_name': 'Nutzer:in',
                                    'order': 2
                                },
                                'address': {
                                    'verbose_name': 'Adresse',
                                    'width': 4,
                                }
                            }
                          },
                         {'object': Tool,
                          'title': 'Werkzeuge/Maschinen',
                          'filter': Q(name_short__icontains=search_text) | Q(name_exact__icontains=search_text),
                          'exclude': ['barcode_img', 'barcode_str', 'pk', 'id', 'categories'],
                          'views': {'detail': 'tool-detail'},
                          'render_options': {
                                'type': {
                                    'order': 4
                                }
                            }
                          },
                         {'object': Consumable,
                          'icon': 'box',
                          'title': 'Verbrauchsmaterial',
                          'filter': Q(name_short__icontains=search_text) | Q(name_exact__icontains=search_text),
                          'exclude': ['pk', 'id', 'thumbnail', 'dimensions_x', 'dimensions_y', 'categories'],
                          'views': {'detail': 'consumable-detail'}
                          },
                         {'object': TimeSlot,
                          'icon': 'clock',
                          'title': 'Zeitbuchungen',
                          'filter': Q(comment__icontains=search_text),
                          'exclude': ['pk', 'id'],
                          'views': {'detail': 'time-slot-detail'}
                          }]

        search_results = []

        for model in search_models:
            if 'annotate' in model:
                model_results = model['object'].objects.annotate(**model['annotate']).filter(model['filter'])
            else:
                model_results = model['object'].objects.filter(model['filter'])

            if len(model_results) > 0:
                result = {}
                if 'exclude' in model:
                    result['exclude'] = model['exclude']
                if 'views' in model:
                    result['views'] = model['views']
                if 'render_options' in model:
                    result['render_options'] = model['render_options']
                if 'title' in model:
                    result['title'] = model['title']
                if 'icon' in model:
                    result['icon'] = model['icon']

                result['result'] = model_results
                search_results.append(result)

        context = {
            'title': 'Suchergebnisse für \'{}\''.format(search_text),
            'icon': 'search',
            'breadcrumbs': {
                'Home': 'werkstatt-user-list',
                'Suchergebnisse': 'global-search'
            },
            'search_results': search_results
        }

        return context

makerspacerp/base/templates/owba_dashboard/base.html
{% load static %}
{% load field_value %}
{% load breadcrumbs %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{% static 'owba_dashboard/img/favicon.ico' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/2fa93aeef4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'owba_dashboard/css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'owba_dashboard/css/style.css' %}">
    <title>owba - {% block title %}{{ title }}{% endblock title %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light" id="main-nav">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'owba_dashboard/img/logo.png' %}" alt="Werkstattmanagement" id="logo">
            </a>
            <form action="{% url 'global-search' %}" method="get" id="global-search">
                <input id="searchbar" name="query" value="{{ request.GET.query }}">
                <button type="submit" class="btn global-search__submit"><i class="fas fa-search"></i></button>
            </form>
            {% include 'owba_dashboard/widgets/avatar.html' %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
    </header>
    <div class="d-flex overflow-auto" id="wrapper">
        <div class="bg-light border-right" id="sidebar-wrapper">
          <div class="list-group list-group-flush" id="sidebar-menu">
            <a href="{% url 'time-slot-list' %}" class="list-group-item list-group-item-action bg-light font-dosis"><i class="fas fa-calendar-alt fas-icon-sidebar"></i> Buchungsplan</a>
            <a href="{% url 'werkstatt-user-list' %}" class="list-group-item list-group-item-action bg-light font-dosis"><i class="fas fa-users fas-icon-sidebar"></i> Werkstattnutzer:innen</a>
            <a href="{% url 'tool-list' %}" class="list-group-item list-group-item-action bg-light font-dosis"><i class="fas fa-tools fas-icon-sidebar"></i> Werkzeug/Maschinen</a>
            <a href="{% url 'storage-list' %}" class="list-group-item list-group-item-action bg-light font-dosis"><i class="fas fa-box fas-icon-sidebar"></i> Lagerverwaltung</a>
            <a href="{% url 'introduction-list' %}" class="list-group-item list-group-item-action bg-light font-dosis"><i class="far fa-lightbulb fas-icon-sidebar"></i> Einweisungen</a>
            <a href="{% url 'transaction-list' %}" class="list-group-item list-group-item-action bg-light font-dosis"><i class="fas fa-euro-sign fas-icon-sidebar"></i> Abrechnung</a>
            <a href="{% url 'settings-detail' %}" class="list-group-item list-group-item-action bg-light font-dosis"><i class="fas fa-sliders-h fas-icon-sidebar"></i> Einstellungen</a>
            <p class="font-dosis p-2 font-size-10">Problem gefunden? Erstelle einen <a href="https://gitlab.com/owba/makerspacerp/-/issues" target="_blank">Bug-Report</a>.</p>
          </div>
        </div>
        <div id="page-content-wrapper" class="container-fluid position-relative overflow-auto">
            {% breadcrumbs %}
            <div class="page-title">
            {% block page_title %}
                <i class="page-title__icon fas fa-{{ icon }}"></i>
                <h1 class="font-dosis m-0">{{ title }}</h1>
            {% endblock page_title %}
            </div>
            {% if toolbar_buttons|length > 0 %}
            <div class="toolbar">
                {% block toolbar %}
                    {% for button_label, data in toolbar_buttons.items %}
                        {% if data.url.arg %}
                        <a href="{% url data.url.path object|field_value:data.url.arg %}" class="btn btn-primary">
                        {% elif data.url.kwargs %}
                        <a href="{% url data.url.path %}?{{ data.url.kwargs }}" class="btn btn-primary">
                        {% else %}
                        <a href="{% url data.url %}" class="btn btn-primary">
                        {% endif %}
                            {% if data.icon %}
                                <i class="fas fa-{{ data.icon }}"></i>
                            {% endif %}
                            {{ button_label }}
                        </a>
                    {% endfor %}
                {% endblock toolbar %}
            </div>
            {% endif %}
            <div class="overflow-auto" id="main-content">
            {% block content %}{% endblock content %}
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

makerspacerp/base/templates/owba_dashboard/global_search_results.html
{% extends 'owba_dashboard/base.html' %}
{% load tabular_list %}

{% block title %}Suchergebnis{% endblock title %}
{% block content %}
    {% for subset in search_results %}
        <h2><i class="fas fa-{{ subset.icon }}"></i> {{ subset.title }}</h2>
        {% tabular_list objects=subset.result render_options=subset.render_options exclude=subset.exclude views=subset.views %}
    {% endfor %}
{% endblock content %}

makerspacerp/base/templates/owba_dashboard/introduction_detail.html
{% extends 'owba_dashboard/generic/detail.html' %}

{% block content %}
    {{ block.super }}
    <h2 class="font-dosis">Inhalte:</h2>
    <ul class="bordered checklist">
    {% for content in object.introductioncontent_set.all %}
        <li>{{ content.text }}</li>
    {% endfor %}
    </ul>
{% endblock %}

makerspacerp/base/templates/owba_dashboard/introduction_pdf.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'owba_dashboard/css/pdf.css' %}">
</head>
<body>
    <div class="pdf-header">
        <img src="{% static 'owba_dashboard/img/logo.png' %}" class="logo">
        <p class="adress-block">
            Offene Werkstatt Bamberg<br/>
            Weißenburgstraße 10<br/>
            96052 Bamberg<br/>
        </p>
    </div>
    <h1 class="font-dosis center">{{ object }}</h1>
    <table class="font-dosis w-100">
        <tr>
            <td class="right">Durchgeführt am:</td>
            <td class="border-bottom w-50"></td>
        </tr>
        <tr>
            <td class="right">Durchgeführt von:</td>
            <td class="border-bottom"></td>
        </tr>
        <tr>
            <td class="right p-correct">Teilnehmende:r Werkstattnutzer:in:</td>
            <td class="border-bottom"></td>
        </tr>
    </table>
    <p class="description font-dosis">{{ object.description }}</p>
    <h2 class="font-dosis">Folgende Inhalte wurden vermittelt:</h2>
    <ul class="checklist">
        {% for content in object.introductioncontent_set.all %}
            <li>{{ content.text }}</li>
        {% endfor %}
    </ul>
    <table class="signatures font-dosis">
        <tr>
            <td>Ort, Datum</td>
            <td>Unterschrift Werkstattnutzer:in</td>
            <td>Unterschrift Durchführende:r</td>
        </tr>
    </table>
</body>
</html>

makerspacerp/base/templates/owba_dashboard/login.html
{% load static %}
{% load breadcrumbs %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{% static 'owba_dashboard/img/favicon.ico' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/2fa93aeef4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'owba_dashboard/css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'owba_dashboard/css/style.css' %}">
    <title>owba - {% block title %}{% endblock title %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light" id="main-nav">
            <a class="navbar-brand" href="#">
                <img src="{% static 'owba_dashboard/img/logo.png' %}" alt="Werkstattmanagement" id="logo">
            </a>
        </nav>
    </header>
    <div class="login-body">
        <div class="login-form w-md-50">
            {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    Your username and password didn't match. Please try again.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}

            {% if next %}
                {% if user.is_authenticated %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        Your account doesn't have access to this page. To proceed,
                        please login with an account that has access.
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% else %}
                    <p>Log dich ein um auf die Seite zuzugreifen.</p>
                {% endif %}
            {% endif %}

            <h1 class="font-dosis">Bitte log dich ein.</h1>
            <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <p>
                {{ form.username.label_tag }}
                {{ form.username }}
            </p>
            <p>
                {{ form.password.label_tag }}
                {{ form.password }}
            </p>

            <input type="submit" class="btn btn-primary" value="Einloggen">
            {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
            {% else %}
            <input type="hidden" name="next" value="/">
            {% endif %}
            </form>
        </div>
    </div>
</body>

makerspacerp/base/templates/owba_dashboard/settings_detail.html
{% extends 'owba_dashboard/generic/detail.html' %}

{% block page_title %}
    <h1 class="font-dosis"><i class="fas fa-{{ icon }}"></i> {{ title }}</h1>
    {% if update_view or delete_view %}
        <div class="detail-tools">
        {% if update_view %}
            <a href="{% url update_view %}"><i class="fas fa-edit"></i></a>
        {% endif %}
        {% if delete_view %}
            <a href="{% url delete_view %}"><i class="fas fa-trash"></i></a>
        {% endif %}
        </div>
    {% endif %}
{% endblock %}

makerspacerp/base/templates/owba_dashboard/transaction_detail.html
{% extends 'owba_dashboard/base.html' %}

{% block title %}Transaktion{% endblock title %}

{% block content %}
    {{ transaction }}
{% endblock content %}